// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1nuRg0bFlZEOr9L1KbFVdGBnjJOJyfA',
    appId: '1:832352391504:web:99d920c2eda78abe08dc55',
    messagingSenderId: '832352391504',
    projectId: 'amritafind-ee505',
    authDomain: 'amritafind-ee505.firebaseapp.com',
    storageBucket: 'amritafind-ee505.firebasestorage.app',
    measurementId: 'G-1K7G198S1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD933XpmUcngfETqUd9SEFosnWJAP8XYQk',
    appId: '1:832352391504:android:b4c95827353623d108dc55',
    messagingSenderId: '832352391504',
    projectId: 'amritafind-ee505',
    storageBucket: 'amritafind-ee505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRVba_j1f0FXIIGo2B86aimhbRq4l_KWI',
    appId: '1:832352391504:ios:e73632787e5eeff608dc55',
    messagingSenderId: '832352391504',
    projectId: 'amritafind-ee505',
    storageBucket: 'amritafind-ee505.firebasestorage.app',
    iosBundleId: 'com.example.lostandfound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRVba_j1f0FXIIGo2B86aimhbRq4l_KWI',
    appId: '1:832352391504:ios:e73632787e5eeff608dc55',
    messagingSenderId: '832352391504',
    projectId: 'amritafind-ee505',
    storageBucket: 'amritafind-ee505.firebasestorage.app',
    iosBundleId: 'com.example.lostandfound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy1nuRg0bFlZEOr9L1KbFVdGBnjJOJyfA',
    appId: '1:832352391504:web:cbce9fcffb05754508dc55',
    messagingSenderId: '832352391504',
    projectId: 'amritafind-ee505',
    authDomain: 'amritafind-ee505.firebaseapp.com',
    storageBucket: 'amritafind-ee505.firebasestorage.app',
    measurementId: 'G-MSK79RB60F',
  );
}
